;BEGIN FRAGMENT CODE - Do not edit anything between this and the end comment
Scriptname Fragments:Quests:QF_TestEnableWithGravJump_00112A54 Extends Quest Hidden Const

;BEGIN FRAGMENT Fragment_Stage_0010_Item_00
Function Fragment_Stage_0010_Item_00()
;BEGIN CODE
SpaceshipReference myShip = Alias_Ship.GetRef() as SpaceshipReference

Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
Utility.wait(5)
myShip.EnableWithGravJump()
Utility.wait(5)
myShip.disableWithGravJump()
;END CODE
EndFunction
;END FRAGMENT

;END FRAGMENT CODE - Do not edit anything between this and the begin comment

ReferenceAlias Property Alias_Ship Auto Const Mandatory
