ScriptName Fragments:Quests:QF_TestEnableWithGravJump_00112A54 Extends Quest Const hidden

;-- Variables ---------------------------------------

;-- Properties --------------------------------------
ReferenceAlias Property Alias_Ship Auto Const mandatory

;-- Functions ---------------------------------------

Function Fragment_Stage_0010_Item_00()
  spaceshipreference myShip = Alias_Ship.GetRef() as spaceshipreference
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
  Utility.wait(5.0)
  myShip.EnableWithGravJump()
  Utility.wait(5.0)
  myShip.disableWithGravJump()
EndFunction
